# Generated by Django 4.0 on 2022-01-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyId', models.CharField(max_length=200)),
                ('Time1', models.CharField(max_length=200)),
                ('Time2', models.CharField(max_length=200)),
                ('Time3', models.CharField(max_length=200)),
                ('Time4', models.CharField(max_length=200)),
                ('Time5', models.CharField(max_length=200)),
            ],
        ),
    ]
