# Generated by Django 4.0 on 2022-01-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
