# Generated by Django 4.0 on 2022-01-08 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('ChainId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('ChainName', models.CharField(max_length=200)),
                ('ChainOpenTime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('RestaurantId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('RestaurantName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('ReservationId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('DateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Rdate', models.CharField(max_length=200)),
                ('Rtime', models.CharField(max_length=200)),
                ('Rname', models.CharField(max_length=100)),
                ('Rpeople', models.CharField(max_length=100)),
                ('Rdetail', models.CharField(default='無', max_length=200)),
                ('ChainId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.chain')),
            ],
        ),
        migrations.AddField(
            model_name='chain',
            name='RestaurantName',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time1', models.CharField(max_length=200)),
                ('Time2', models.CharField(max_length=200)),
                ('Time3', models.CharField(max_length=200)),
                ('Time4', models.CharField(max_length=200)),
                ('Time5', models.CharField(max_length=200)),
                ('RestaurantName', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
