# Generated by Django 4.0 on 2022-01-07 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('CompanyName', models.CharField(max_length=200)),
                ('CompanyOpenTime', models.CharField(max_length=100)),
                ('CompanyAddress', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('RoomName', models.CharField(max_length=200)),
                ('CompanyName', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='room.company')),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('ReservationId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('DateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Rdate', models.CharField(max_length=200)),
                ('Rtime', models.CharField(max_length=200)),
                ('Rname', models.CharField(max_length=100)),
                ('Rpeople', models.CharField(max_length=100)),
                ('Rtitle', models.CharField(max_length=200)),
                ('RoomId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time1', models.CharField(max_length=200)),
                ('Time2', models.CharField(max_length=200)),
                ('Time3', models.CharField(max_length=200)),
                ('Time4', models.CharField(max_length=200)),
                ('Time5', models.CharField(max_length=200)),
                ('CompanyName', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='room.company')),
            ],
        ),
    ]
