# Generated by Django 4.0 on 2022-01-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='Rdetail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
