# Generated by Django 4.0 on 2022-01-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_roomreservation_rdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='Rdetail',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
